services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    image: javierjrueda/comfyui-runpod:latest
    ports:
      - "3000:3000"
      - "8888:8888"
    volumes:
      - ./test-volume:/runpod-volume
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
