services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    image: javierjrueda/comfyui-runpod:latest
    ports:
      - "3000:3000"
      - "8888:8888"
    volumes:
      - ./test-volume:/runpod-volume
